language: php

php:
  - 7.0
  - 7.1

services:
  - mysql
  
before_install:
  - mysql -u root 'CREATE DATABASE IF NOT EXISTS sqllion;'
  - mysql -u root 'CREATE USER IF NOT EXISTS 'gary'@'localhost' IDENTIFIED WITH mysql_native_password BY 'garypass';'
  - mysql -u root 'GRANT SELECT, INSERT, UPDATE ON sqllion TO 'gary'@'localhost';'
  
  - mysql sqllion < sqllion_user_setup.sql
  
jobs:
  include:
    - stage: Database Connection
      script:
      - php connect_db.php
    - stage: Key Commands
      script:
      - php database_tools.php

os:
  - windows
